version: '3.1'
services:
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3307:3306"
    volumes:
      - talententdecker_db:/var/lib/mysql
  app:
    build:
      context: jekyll
      dockerfile: Dockerfile.dev
    environment:
      RAILS_PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - gems_app:/bundle # persist gems as a volume
      - ./jekyll:/app
      - ../talententdecker/docker-entrypoint-dev.sh:/usr/local/bin/docker-entrypoint-dev.sh
volumes:
  gems_app:
  talententdecker_db:
