# Build a development docker image
FROM ruby:2.5.1-stretch

RUN curl -sL https://deb.nodesource.com/setup_9.x | bash - \
    && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -\
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update -qq \
    && apt-get install -y --no-install-recommends build-essential nodejs yarn \
    && apt-get clean

# no need to copy files now as docker-compose will handle the mounting
ENV APPDIR=/app \
    # BUNDLE_PATH=/bundle \
    # BUNDLE_BIN=/bundle/bin \
    # GEM_HOME=/bundle \
    TERM=xterm
# ENV PATH="${BUNDLE_BIN}:${PATH}"

WORKDIR $APPDIR

ENTRYPOINT ["docker-entrypoint-dev.sh"]
