version: '3.1'
services:
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3307:3306"
    volumes:
      - talententdecker_db:/var/lib/mysql
  rails5:
    build:
      context: rails5
      dockerfile: Dockerfile.dev
    environment:
      RAILS_PORT: 3000
      RAILS_DB_HOST: 'mysql'
    ports:
      - "3000:3000"
    volumes:
      - talententdecker_gems:/usr/local/bundle # persist gems as a volume
      - ./rails5:/app
      - ../talententdecker/docker-entrypoint-dev.sh:/usr/local/bin/docker-entrypoint-dev.sh
volumes:
  talententdecker_gems:
  talententdecker_db:
